language: php

sudo: false

cache:
    directories:
        - vendor

matrix:
    include:
        - php: 7.1
          env:
              - COMPOSER_FLAGS='--prefer-lowest'
        - php: 7.2

before_script:
    - phpenv config-rm xdebug.ini
    - composer validate
    - composer update $COMPOSER_FLAGS

script: vendor/bin/phpspec run -f pretty
